# Generated by Django 4.0.6 on 2022-07-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurlAPI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('long_url', models.URLField(max_length=1000)),
                ('short_url', models.URLField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'main_urls',
            },
        ),
    ]
